Update testing_vars.yml

diff --git a/.github/workflows/testing_vars.yml b/.github/workflows/testing_vars.yml
--- a/.github/workflows/testing_vars.yml
+++ b/.github/workflows/testing_vars.yml
@@ -59,6 +59,13 @@ jobs:
           echo " Run update var value ${{ env.run_update }}"
 
 
+      - name: job failure
+        run: exit 1
+
+      - name: after failure
+        run: echo "this step should not be reached after failure"
+
+
       # Checkout the python tools repo
       # used to authenticate and validate the PR
       # -------------------------------------------      
